[package]
name = "ruvc"
version = "0.1.0"
edition = "2018"

[dependencies]
rusb = "0.9.0"
log = "0.4.14"
zerocopy = "0.6.0"
bitflags = "1.3.2"
uuid = "0.8.2"
byteorder = "1.4.3"

[dev-dependencies]
env_logger = "0.9.0"
uuid = "0.8.2"
